export default {
  "login": "Sudiptobanerjee123",
  "id": 35999718,
  "node_id": "MDQ6VXNlcjM1OTk5NzE4",
  "avatar_url": "https://avatars.githubusercontent.com/u/35999718?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Sudiptobanerjee123",
  "html_url": "https://github.com/Sudiptobanerjee123",
  "followers_url": "https://api.github.com/users/Sudiptobanerjee123/followers",
  "following_url": "https://api.github.com/users/Sudiptobanerjee123/following{/other_user}",
  "gists_url": "https://api.github.com/users/Sudiptobanerjee123/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Sudiptobanerjee123/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Sudiptobanerjee123/subscriptions",
  "organizations_url": "https://api.github.com/users/Sudiptobanerjee123/orgs",
  "repos_url": "https://api.github.com/users/Sudiptobanerjee123/repos",
  "events_url": "https://api.github.com/users/Sudiptobanerjee123/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Sudiptobanerjee123/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sudipta Banerjee",
  "company": null,
  "blog": "",
  "location": "Kolkata",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 14,
  "public_gists": 0,
  "followers": 2,
  "following": 2,
  "created_at": "2018-01-31T13:05:27Z",
  "updated_at": "2023-11-07T22:58:40Z"
};
